GerenciadorPalpites.Web/Models/ViewModel/ClassificacaoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GerenciadorPalpites.Web.Models
{
    public class ClassificacaoViewModel
    {
        public int Id { get; set; }
        public int IdBolao { get; set; }
        public int IdUsuario { get; set; }
        public int Total { get; set; }
        public int PlacarCheio { get; set; }
        public int PlacarVencedor { get; set; }
        public int PlacarPerdedor { get; set; }
        public int Variacao { get; set; }
        public int AcertouVencedor { get; set; }
        public string NomeUsuario { get; set; }
        public int Posicao { get; set; }
        public int PosicaoAnterior { get; set; }
    }
}

GerenciadorPalpites.Web/Controllers/Cadastro/CadBolaoController.cs
using AutoMapper;
using GerenciadorPalpites.Web.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace GerenciadorPalpites.Web.Controllers
{
    public class CadBolaoController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult MeusBoloes(string ordenacao, string filtro, string termoPesquisa, string tamanhoPagina, int? page)
        {
            ViewBag.CurrentSort = ordenacao;
            ViewBag.NameSortParam = string.IsNullOrEmpty(ordenacao) ? "nome desc" : "";
            ViewBag.ChampionshipSortParam = ordenacao == "campeonato" ? "campeonato desc" : "campeonato";

            //ComboBox para definir o tamanho das páginas
            if (tamanhoPagina != null)
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, int.Parse(tamanhoPagina));
            else
            {
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
                tamanhoPagina = _quantMaxLinhasPorPagina.ToString();
            }

            ViewBag.CurrentPageSize = tamanhoPagina;

            if (termoPesquisa != null)
                page = 1;
            else
                termoPesquisa = filtro;

            ViewBag.CurrentFilter = termoPesquisa;

            List<BolaoViewModel> lista = Mapper.Map<List<BolaoViewModel>>(BolaoModel.RecuperarListaMeusBoloes(User.Identity.Name, filtro: termoPesquisa, ordem: ordenacao));

            int pageNumber = (page ?? 1);
            //Retorna os registros paginados
            return View(lista.ToPagedList(pageNumber, int.Parse(tamanhoPagina)));
        }

        public ActionResult Index(string ordenacao, string filtro, string termoPesquisa, string tamanhoPagina, int? page)
        {
            ViewBag.CurrentSort = ordenacao;
            ViewBag.NameSortParam = string.IsNullOrEmpty(ordenacao) ? "nome desc" : "";
            ViewBag.ChampionshipSortParam = ordenacao == "campeonato" ? "campeonato desc" : "campeonato";

            //ComboBox para definir o tamanho das páginas
            if (tamanhoPagina != null)
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, int.Parse(tamanhoPagina));
            else
            {
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
                tamanhoPagina = _quantMaxLinhasPorPagina.ToString();
            }

            ViewBag.CurrentPageSize = tamanhoPagina;

            if (termoPesquisa != null)
                page = 1;
            else
                termoPesquisa = filtro;

            ViewBag.CurrentFilter = termoPesquisa;

            List<BolaoViewModel> lista = Mapper.Map<List<BolaoViewModel>>(BolaoModel.RecuperarLista(User.Identity.Name, filtro: termoPesquisa, ordem: ordenacao));
            ViewBag.Campeonato = Mapper.Map<List<CampeonatoViewModel>>(CampeonatoModel.RecuperarLista());

            int pageNumber = (page ?? 1);
            //Retorna os registros paginados
            return View(lista.ToPagedList(pageNumber, int.Parse(tamanhoPagina)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarBolao(BolaoViewModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var url = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var bolao = Mapper.Map<BolaoModel>(model);
                    bolao.Publico = !bolao.Publico;
                    var id = bolao.Salvar();

                    if (model.AlterarPontuacao)
                    {
                        CriarRegra(model.PlacarExato, model.AcertouVencedor, model.GolsFeitos, id);
                    }
                    else {
                        RegrasBolaoViewModel regraBolaoModel = new RegrasBolaoViewModel();
                        regraBolaoModel.IdBolao = id;
                        regraBolaoModel.IdRegra = 1;

                        var regraBolao = Mapper.Map<RegrasBolaoModel>(regraBolaoModel);
                        regraBolao.Salvar();
                    }

                    UsuarioBolaoModel usuario = new UsuarioBolaoModel();
                    int idUser = usuario.RecuperarIDPeloNome(User.Identity.Name);

                    UsuarioBolaoViewModel usuarioBolaoModel = new UsuarioBolaoViewModel();
                    usuarioBolaoModel.IdBolao = id;
                    usuarioBolaoModel.IdUsuario = idUser;

                    var usuarioMap = Mapper.Map<UsuarioBolaoModel>(usuarioBolaoModel);
                    usuarioMap.Salvar();

                    if (id > 0)
                    {
                        url = new UrlHelper(Request.RequestContext).Action("Index", "CadBolao");
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, Url = url });
        }
        [HttpPost]
        public JsonResult VerficarBolaoPublico(int idBolao)
        {
            return Json(new { IsPublic = BolaoModel.VerificaBolaoPublico(idBolao) });
        }
        public void CriarRegra(float valor1, float valor2, float valor3, int idBolao)
        {
            RegrasViewModel regraModel = new RegrasViewModel();
            regraModel.Pontuacao1 = valor1;
            regraModel.Pontuacao2 = valor2;
            regraModel.Pontuacao3 = valor3;

            var regra = Mapper.Map<RegrasModel>(regraModel);
            int idRegra = regra.RecuperarIDPelosValores(regraModel);

            if (idRegra == 0)
            {
                idRegra = regra.Salvar();
            }

            RegrasBolaoViewModel regraBolaoModel = new RegrasBolaoViewModel();
            regraBolaoModel.IdBolao = idBolao;
            regraBolaoModel.IdRegra = idRegra;

            var regraBolao = Mapper.Map<RegrasBolaoModel>(regraBolaoModel);
            regraBolao.Salvar();
        }
    }
}

GerenciadorPalpites.Web/Controllers/Cadastro/ClassificacaoController.cs
using AutoMapper;
using GerenciadorPalpites.Web.Models;
using PagedList;
using System.Collections.Generic;
using System.Web.Mvc;

namespace GerenciadorPalpites.Web.Controllers
{
    [Authorize(Roles = "Gerente,Adm,Operador")]
    public class ClassificacaoController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index(string ordenacao, string tamanhoPagina, int? idBolao, int? page)
        {
            ViewBag.IdBolao = idBolao ?? 0;
            ViewBag.CurrentSort = ordenacao;
            ViewBag.PosicaoSortParam = string.IsNullOrEmpty(ordenacao) ? "posicao desc" : "";
            ViewBag.TotalSortParam = ordenacao == "total" ? "total desc" : "total";
            ViewBag.VariacaoSortParam = ordenacao == "variacao" ? "variacao desc" : "variacao";
            ViewBag.NameSortParam = ordenacao == "nome" ? "nome desc" : "nome";
            ViewBag.PCSortParam = ordenacao == "placarCheio" ? "placarCheio desc" : "placarCheio";
            ViewBag.PVSortParam = ordenacao == "placarVencedor" ? "placarVencedor desc" : "placarVencedor";
            ViewBag.PPSortParam = ordenacao == "placarPerdedor" ? "placarPerdedor desc" : "placarPerdedor";
            ViewBag.AVSortParam = ordenacao == "acertouVencedor" ? "acertouVencedor desc" : "acertouVencedor";

            //ComboBox para definir o tamanho das páginas
            if (tamanhoPagina != null)
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, int.Parse(tamanhoPagina));
            else
            {
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
                tamanhoPagina = _quantMaxLinhasPorPagina.ToString();
            }

            ViewBag.CurrentPageSize = tamanhoPagina;

            List<ClassificacaoViewModel> lista = Mapper.Map<List<ClassificacaoViewModel>>(ClassificacaoModel.RecuperarLista(filtro: ViewBag.IdBolao, ordem: ordenacao));

            int pageNumber = (page ?? 1);
            //Retorna os registros paginados
            return View(lista.ToPagedList(pageNumber, int.Parse(tamanhoPagina)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ClassificacaoPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = Mapper.Map<List<BolaoViewModel>>(BolaoModel.RecuperarLista(User.Identity.Name, pagina, tamPag, filtro, ordem));

            return Json(lista);
        }
    }
}

GerenciadorPalpites.Web/Views/CadBolao/Classificacao.cshtml
@model List<GerenciadorPalpites.Web.Models.ClassificacaoViewModel>
@{
    Layout = "~/Views/Shared/_Classificacao.cshtml";
    ViewBag.Title = "Classifição";
    ViewBag.Lista = Model;
}
@section Styles {
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Content/Cadastro/Classificacao.css" rel="stylesheet" />
}
@section TituloGrid {
    <th><span class="coluna-ordenacao" data-campo="variacao">Variação</span></th>
    <th><span class="coluna-ordenacao" data-campo="posicao">#</span></th>
    <th><span class="coluna-ordenacao" data-campo="nome">Nome</span></th>
    <th><span class="coluna-ordenacao" data-campo="total">Total</span></th>
    <th><span class="coluna-ordenacao" data-campo="placarCheio">PC</span></th>
    <th><span class="coluna-ordenacao" data-campo="placarVencedor">PV</span></th>
    <th><span class="coluna-ordenacao" data-campo="placarPerdedor">PP</span></th>
    <th><span class="coluna-ordenacao" data-campo="acertouVencedor">AV</span></th>
}
@section Scripts{
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script>
        var tituloPagina = '@ViewBag.Title';
        var url_page_click = '@Url.Action("ClassificacaoPagina", "Classificacao")';
        var url_tam_pag_change = '@Url.Action("ClassificacaoPagina", "Classificacao")';
        var url_filtro_change = '@Url.Action("ClassificacaoPagina", "Classificacao")';
        var linhas = [];

        @{
            var linha = 0;
            foreach (var item in Model)
            {
                linha++;
                if (linha <= ViewBag.QuantMaxLinhasPorPagina)
                {
                    @:linhas.push(@Html.Raw(Json.Encode(item)));
                }
                else
                {
                    break;
                }
            }
        }
    </script>
    <script id="template-grid-alterar" type="x-tmpl-mustache">
        <tr data-id="{{ Id }}">
            <td>{{ Variacao }}</td>
            <td>{{ Posicao }}</td>
            <td>{{ Nome }}</td>
            <td>{{ Total }}</td>
            <td>{{ PlacarCheio }}</td>
            <td>{{ PlacarVencedor }}</td>
            <td>{{ PlacarPerdedor }}</td>
            <td>{{ AcertouVencedor }}</td>
        </tr>
    </script>
}

GerenciadorPalpites.Web/Views/CadBolao/Index.cshtml
@model PagedList.IPagedList<GerenciadorPalpites.Web.Models.BolaoViewModel>
@using PagedList.Mvc;

@{
    Layout = "~/Views/Shared/_Cadastro.cshtml";

    ViewBag.Title = "Bolões";
    ViewBag.Lista = Model;
    ViewBag.ControllerName = "CadBolao";
    ViewBag.ControllerNameUsuarioBolao = "CadUsuarioBolao";
    ViewBag.ActionName = "Index";
}

@section Styles {
    <link href="~/Content/Cadastro/Bolao.css" rel="stylesheet" />
}

@section TituloGrid {
    <th>
        @Html.ActionLink("Nome", "Index", new { ordenacao = ViewBag.NameSortParam, filtro = ViewBag.CurrentFilter, tamanhoPagina = ViewBag.CurrentPageSize }, new { @class = "coluna-grid", data_column_sort = "nome" })
    </th>
    <th>
        @Html.ActionLink("Campeonato", "Index", new { ordenacao = ViewBag.ChampionshipSortParam, filtro = ViewBag.CurrentFilter, tamanhoPagina = ViewBag.CurrentPageSize }, new { @class = "coluna-grid", data_column_sort = "campeonato" })
    </th>
    <th>Ação</th>
}

@section Paginacao {
    Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, ordenacao = ViewBag.CurrentSort, filtro = ViewBag.CurrentFilter, tamanhoPagina = ViewBag.CurrentPageSize }))
}

@section CamposCadastro {
    <div class="row">
        <div class="col-md-12">
            @Html.Label("txt_nome", "Nome", new { @class = "control-label" })
            @Html.TextBox("txt_nome", null, new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" style="margin-top: 10px; margin-bottom: 10px;">
            @Html.Label("ddl_campeonato", "Campeonato", new { @class = "control-label" })
            @Html.DropDownList("ddl_campeonato", new SelectList(ViewBag.Campeonato, "Id", "Nome"), new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="col-md-2">
                @Html.Label("lbl_privado", "Privado?", new { @class = "control-label" })
                @Html.CheckBox("chk_privado", false, new { @id = "chk_privado", @class = "form-control form-check-input", @onchange = "visibilidadeSenha();" })
            </div>
        </div>
        <div class="col">
            <div class="col-md-4">
                @Html.Label("lbl_AlterarPontuacao", "Alterar pontuações?", new { @class = "control-label" })
                @Html.CheckBox("chk_alterarPontuacao", false, new { @id = "chk_alterarPontuacao", @class = "form-control form-check-input", @onchange = "visibilidadePontuacao();" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.Label("lbl_senha", "Senha", new { @id = "lbl_senha", @class = "control-label", @style = "display: none" })
            @Html.Password("txt_senha", null, new { @class = "form-control", @style = "display: none" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.Label("lbl_placarExato", "Placar Exato", new { @id = "lbl_placarExato", @class = "control-label", @style = "display: none" })
            @Html.TextBox("txt_placarExato", 5, new { @class = "form-control", @style = "display: none" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.Label("lbl_acertarVencedor", "Acertar o vencedor", new { @id = "lbl_acertarVencedor", @class = "control-label", @style = "display: none" })
            @Html.TextBox("txt_acertarVencedor", 3, new { @class = "form-control", @style = "display: none" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.Label("lbl_golsTimes", "Acertar Gols de um dos Times", new { @id = "lbl_golsTimes", @class = "control-label", @style = "display: none" })
            @Html.TextBox("txt_golsTimes", 1, new { @class = "form-control", @style = "display: none" })
        </div>
    </div>
}

<div id="modal_cadastro_participar" class="invisivel" role="dialog">
    <div id="msg_mensagem_aviso_participar" class="text-danger invisivel"></div>
    <fieldset>
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-md-12">
                @Html.Label("lbl_senha", "Senha", new { @class = "control-label" })
                @Html.Password("txt_senha_participar", "", new { @class = "form-control" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="modal-footer">
                        <button id="btn_sair" class="btn btn-default" role="button" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i> Sair</button>
                        <button id="btn_confirmar_participar" class="btn btn-primary btn_confirmar_participar" role="button" onclick="participarComSenha()"><i class="glyphicon glyphicon-ok"></i> Participar</button>
                    </div>
                    <div id="msg_aviso_participar" class="alert alert-warning invisivel">Falta preencher o campo acima.</div>
                    <div id="msg_erro_participar" class="alert alert-danger invisible">Ops! Deu ruim!</div>
                </div>
            </div>
        </div>
    </fieldset>
</div>

@section Scripts{
    <script id="template-grid-alterar" type="x-tmpl-mustache">
        <tr data-id="{{ Id }}">
            <td>{{ Nome }}</td>
            <td>{{ NomeCampeonato }}</td>
            <td>
                <a class="btn btn-success btn-participar" role="button" id="btn-participar"><i class="glyphicon glyphicon-plus"></i> Participar</a>
            </td>
        </tr>
    </script>
    <script>
        document.getElementById('txt_placarExato').oninput = function () {
            this.value = this.value.replace(/[^0-9]+/g, '');
        }
        document.getElementById('txt_acertarVencedor').oninput = function () {
            this.value = this.value.replace(/[^0-9]+/g, '');
        }
        document.getElementById('txt_golsTimes').oninput = function () {
            this.value = this.value.replace(/[^0-9]+/g, '');
        }
        function visibilidadeSenha() {
            if ($('#chk_privado').is(':checked')) {
                $('#lbl_senha').show();
                $('#txt_senha').show();
                $('#txt_senha_participar').show();
            }
            else {
                $('#lbl_senha').hide();
                $('#txt_senha').hide();
                $('#txt_senha_participar').hide();
            }
        }
        function visibilidadePontuacao() {
            if ($('#chk_alterarPontuacao').is(':checked')) {
                $('#lbl_placarExato').show();
                $('#txt_placarExato').show();

                $('#lbl_acertarVencedor').show();
                $('#txt_acertarVencedor').show();

                $('#lbl_golsTimes').show();
                $('#txt_golsTimes').show();
            }
            else {
                $('#lbl_placarExato').hide();
                $('#txt_placarExato').hide();

                $('#lbl_acertarVencedor').hide();
                $('#txt_acertarVencedor').hide();

                $('#lbl_golsTimes').hide();
                $('#txt_golsTimes').hide();
            }
        }
        var tituloPagina = '@ViewBag.Title';
        var urlSalvar = '@Url.Action("SalvarBolao", ViewBag.ControllerName)';
        var url_participar = '@Url.Action("SalvarUsuarioBolao", ViewBag.ControllerNameUsuarioBolao)'
        var url_VerificaPublico = '@Url.Action("VerficarBolaoPublico", ViewBag.ControllerName)'
        var nomeUsuario = '@User.Identity.Name'
        var idBolao = 0;
    </script>
    <script src="~/Scripts/Cadastro/Bolao.js"></script>
}

GerenciadorPalpites.Web/Views/CadBolao/MeusBoloes.cshtml
@model PagedList.IPagedList<GerenciadorPalpites.Web.Models.BolaoViewModel>
@using PagedList.Mvc;

@{
    Layout = "~/Views/Shared/_CadastroSemIncluir.cshtml";

    ViewBag.Title = "Meus Bolões";
    ViewBag.Lista = Model;
    ViewBag.ControllerName = "CadBolao";
    ViewBag.ActionName = "MeusBoloes";
}

@section Styles {
    <link href="~/Content/Cadastro/Bolao.css" rel="stylesheet" />
}

@section FiltroTamanhoPagina {
    @using (Html.BeginForm(ViewBag.ActionName as string, ViewBag.ControllerName as string, FormMethod.Get, new { @name = "FormTamPag" }))
    {
        @Html.DropDownList("ddl_tam_pag", (SelectList)ViewBag.ListaTamPag, new { @class = "selectpicker", @onchange = "tamanhoPaginaChanged()" })
        @Html.Hidden("tamanhoPagina", ViewBag.CurrentPageSize as string, new { @id = "hiddenTamanhoPagina" });
        @Html.Hidden("ordenacao", ViewBag.CurrentSort as string);
        @Html.Hidden("filtro", ViewBag.CurrentFilter as string);
    }
}

@section TituloGrid {
    <th>
        @Html.ActionLink("Nome", "MeusBoloes", new { ordenacao = ViewBag.NameSortParam, filtro = ViewBag.CurrentFilter, tamanhoPagina = ViewBag.CurrentPageSize }, new { @class = "coluna-grid", data_column_sort = "nome" })
    </th>
    <th>
        @Html.ActionLink("Campeonato", "MeusBoloes", new { ordenacao = ViewBag.ChampionshipSortParam, filtro = ViewBag.CurrentFilter, tamanhoPagina = ViewBag.CurrentPageSize }, new { @class = "coluna-grid", data_column_sort = "campeonato" })
    </th>
    <th>Ação</th>
}

@section Paginacao {
    Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("MeusBoloes", new { page, ordenacao = ViewBag.CurrentSort, filtro = ViewBag.CurrentFilter, tamanhoPagina = ViewBag.CurrentPageSize }))
}

@section Scripts{
    <script id="template-grid-alterar" type="x-tmpl-mustache">
        <tr data-id="{{ Id }}">
            <td>{{ Nome }}</td>
            <td>{{ NomeCampeonato }}</td>
            <td>
                <a class="btn btn-success btn-entrar" id="btn_entrar" role="button"><i class="glyphicon glyphicon-plus"></i> Entrar</a>
            </td>
        </tr>
    </script>

    <script>
        var urlPalpite = '@Url.Action("Index", "Palpite")';
    </script>
}