GerenciadorPalpites.Web/Models/ViewModel/PalpitesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GerenciadorPalpites.Web.Models
{
    public class PalpitesViewModel
    {
        public int Id { get; set; }
        public int IdTimeCasa { get; set; }
        public string NomeTimeCasa { get; set; }
        public int IdTimeFora { get; set; }
        public string NomeTimeFora { get; set; }
        public int IdBolao { get; set; }
        public int IdUsuario { get; set; }
        public int PalpiteTimeCasa { get; set; }
        public int PalpiteTimeFora { get; set; }
        public int IdPartida { get; set; }
        public string NomeRodada { get; set; }
        public bool Contabilizado { get; set; }
        public string Data { get; set; }
        public List<PartidaViewModel> UltimasPartidas { get; set; }
    }
}

GerenciadorPalpites.Web/Controllers/Cadastro/PalpiteController.cs
using AutoMapper;
using GerenciadorPalpites.Web.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace GerenciadorPalpites.Web.Controllers
{
    [Authorize(Roles = "Gerente,Adm,Operador")]
    public class PalpiteController : Controller
    {
        public ActionResult Index(long? idBolao)
        {
            if (idBolao.HasValue)
            {
                ViewBag.IdBolao = idBolao;
                //Buscar o id do campeonato (a partir do Id do bolão informado)
                var idCampeonato = BolaoModel.RecuperarIdCampeonato(idBolao ?? default(int));
                //Buscar as partidas do campeonato (a partir do id do campeonato recuperado acima e filtrar até uma semana após)
                List<PartidaViewModel> partidas = Mapper.Map<List<PartidaViewModel>>(PartidaModel.RecuperarPartidasParaPalpite(idCampeonato));
                List<PalpitesViewModel> palpites = new List<PalpitesViewModel>();

                foreach (var partida in partidas)
                {
                    PalpitesViewModel palpiteView = null;
                    var palpite = PalpitesModel.RecuperarPalpiteUsuarioPeloIdPartida(User.Identity.Name, partida.Id, idBolao.Value);
                    if (palpite != null)
                    {
                        palpiteView = Mapper.Map<PalpitesViewModel>(palpite);
                        palpiteView.NomeRodada = partida.NomeRodada;
                        palpiteView.NomeTimeCasa = partida.NomeTimeCasa;
                        palpiteView.NomeTimeFora = partida.NomeTimeFora;
                        palpiteView.Data = $"Data: {partida.Data.ToString()}";
                    }
                    else
                    {
                        palpiteView = new PalpitesViewModel
                        {
                            Id = 0,
                            IdPartida = partida.Id,
                            IdTimeCasa = partida.IdTimeCasa,
                            NomeTimeCasa = partida.NomeTimeCasa,
                            IdTimeFora = partida.IdTimeFora,
                            NomeTimeFora = partida.NomeTimeFora,
                            NomeRodada = partida.NomeRodada,
                            PalpiteTimeCasa = 0,
                            PalpiteTimeFora = 0,
                            Data = partida.Data.ToString()
                        };
                    }

                    //Buscar as últimas 5 partidas entre
                    palpiteView.UltimasPartidas = Mapper.Map<List<PartidaViewModel>>(PartidaModel.RecuperarUltimasPartidasEntreTimes(partida.IdTimeCasa, partida.IdTimeFora));
                    palpites.Add(palpiteView);
                }

                return View(palpites);
            }
            else
            {
                return View(new List<PalpitesViewModel>());
            }
        }

        [HttpPost]
        public JsonResult SalvarPalpites(List<PalpitesViewModel> palpites)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var url = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    int idUser = UsuarioModel.RecuperarIdPeloNome(User.Identity.Name);
                    foreach (var palpite in palpites)
                    {
                        var palpiteMap = Mapper.Map<PalpitesModel>(palpite);
                        palpiteMap.IdUsuario = idUser;
                        palpiteMap.Salvar();
                    }
                }
                catch
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens });
        }
    }
}

GerenciadorPalpites.Web/Views/Palpite/Index.cshtml
@model List<GerenciadorPalpites.Web.Models.PalpitesViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Title = "Palpites";
    ViewBag.Lista = Model;
}

<link href="~/Content/Cadastro/BaseCadastro.css" rel="stylesheet" />

<div id="cadastro">
    <section>
        <div class="row">
            <div class="col-md-10"><h1>@ViewBag.Title</h1></div>
            <div class="col-md-2" style="padding-top: 24px;"><button id="btn_classificacao" class="btn btn-info" type="submit">Classificação</button></div>
        </div>
    </section>
    <section id="cadastro_conteudo">
        <div id="msg_erro_salvar_palpites" class="alert alert-warning invisivel"></div>
        <div class="row">
            <div class="col-md-12">
                @foreach (var item in Model)
                {
                    <div class="panel panel-default palpite" data-idPartida="@item.IdPartida" data-item='{ "id": @item.Id, "idPartida": @item.IdPartida, "idTimeCasa": @item.IdTimeCasa, "idTimeFora": @item.IdTimeFora, "timeCasa": "@item.NomeTimeCasa", "timeFora": "@item.NomeTimeFora" }'>
                        <div class="panel-body">
                            <div class="row" style="padding: 0px 15px;">
                                <div class="col-md-4" style="padding-top: 7px;">
                                    @item.NomeRodada
                                </div>
                                <div class="col-md-6" style="padding-top: 7px;">
                                    @item.Data
                                </div>
                                <div class="col-md-2">
                                    <button class="btn btn-primary" style="float: right;" type="button" tabindex="-1" data-toggle="collapse" data-target=@($"#collapseUltimasPartidas{item.IdPartida}") aria-expanded="false" aria-controls="@($"collapseUltimasPartidas{item.IdPartida}")">Histórico</button>
                                </div>
                            </div>
                            <div class="row" style="padding-top: 8px;">
                                <div class="col-md-5" style="padding-top: 3px; padding-left: 147px;">@item.NomeTimeCasa</div>
                                <div class="col-md-2">
                                    @Html.TextBox("palpiteTimeCasa", item.PalpiteTimeCasa, new { style = "width: 30px; text-align: center;" })
                                    X
                                    @Html.TextBox("palpiteTimeFora", item.PalpiteTimeFora, new { style = "width: 30px; text-align: center;" })
                                </div>
                                <div class="col-md-5" style="padding-top: 3px; padding-left: 50px;">@item.NomeTimeFora</div>
                            </div>
                            <div class="row collapse" id="@($"collapseUltimasPartidas{item.IdPartida}")">
                                <div class="col-md-12">
                                    @if (item.UltimasPartidas != null)
                                    {
                                        <h4> Últimas @item.UltimasPartidas.Count partidas</h4>

                                        foreach (var partida in item.UltimasPartidas)
                                        {
                                            <div class="row">
                                                <div class="col-md-2">@partida.Data.ToShortDateString()</div>
                                                <div class="col-md-3">@partida.NomeTimeCasa</div>
                                                <div class="col-md-1">
                                                    @partida.PlacarTimeCasa X @partida.PlacarTimeFora
                                                </div>
                                                <div class="col-md-3">@partida.NomeTimeFora</div>
                                                <div class="col-md-3">@partida.NomeCampeonato</div>
                                            </div>
                                        }
                                    }
                                    else
                                    {
                                        <div class="row">Não há histórico de partidas entre esses times.</div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <div id="mensagem_grid" style="margin-bottom: 12px;" @Html.Raw(ViewBag.Lista != null && ViewBag.Lista.Count > 0 ? "class=\"invisivel\"" : "")>
                    Nenhum registro em @ViewBag.Title
                </div>
                @if (ViewBag.Lista != null && ViewBag.Lista.Count > 0)
                {
                    <button id="btn_salvar_palpites" style="float: right;" class="btn btn-success">Salvar</button>
                }
            </div>
        </div>
    </section>
</div>

@section Scripts {
    <script src="~/Scripts/Cadastro/Palpite.js"></script>
    <script>
        document.getElementById('palpiteTimeFora').oninput = function () {
            this.value = this.value.replace(/[^0-9]+/g, '');
        }
        document.getElementById('palpiteTimeCasa').oninput = function () {
            this.value = this.value.replace(/[^0-9]+/g, '');
        }
    </script>
    <script>
        var urlClassificacao = '@Url.Action("Index", "Classificacao", new { idBolao = ViewBag.IdBolao })';
        var urlSalvarPalpites = '@Url.Action("SalvarPalpites", "Palpite")';
        var idBolao = @ViewBag.IdBolao;
    </script>
}