GerenciadorPalpites.Web/Controllers/Cadastro/CadCampeonatoController.cs
using AutoMapper;
using GerenciadorPalpites.Web.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace GerenciadorPalpites.Web.Controllers
{
    [Authorize(Roles = "Gerente,Adm,Operador")]
    public class CadCampeonatoController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index(string ordenacao, string filtro, string termoPesquisa, string tamanhoPagina, int? page)
        {
            ViewBag.CurrentSort = ordenacao;
            ViewBag.NameSortParam = string.IsNullOrEmpty(ordenacao) ? "nome desc" : "";
            ViewBag.SportSortParam = ordenacao == "esporte" ? "esporte desc" : "esporte";

            //ComboBox para definir o tamanho das páginas
            if (tamanhoPagina != null)
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, int.Parse(tamanhoPagina));
            else
            {
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
                tamanhoPagina = _quantMaxLinhasPorPagina.ToString();
            }

            ViewBag.CurrentPageSize = tamanhoPagina;

            if (termoPesquisa != null)
                page = 1;
            else
                termoPesquisa = filtro;

            ViewBag.CurrentFilter = termoPesquisa;

            List<CampeonatoViewModel> lista = Mapper.Map<List<CampeonatoViewModel>>(CampeonatoModel.RecuperarLista(filtro: termoPesquisa, ordem: ordenacao));

            int pageNumber = (page ?? 1);
            //Retorna os registros paginados
            return View(lista.ToPagedList(pageNumber, int.Parse(tamanhoPagina)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CampeonatoPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = Mapper.Map<List<CampeonatoViewModel>>(CampeonatoModel.RecuperarLista(pagina, tamPag, filtro, ordem));

            return Json(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarCampeonato(int id)
        {
            var vm = Mapper.Map<CampeonatoViewModel>(CampeonatoModel.RecuperarPeloId(id));

            return Json(vm);
        }

        [HttpPost]
        [Authorize(Roles = "Gerente,Adm")]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirCampeonato(int id)
        {
            return Json(CampeonatoModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarCampeonato(CampeonatoViewModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var vm = Mapper.Map<CampeonatoModel>(model);
                    var id = vm.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

GerenciadorPalpites.Web/Controllers/Cadastro/CadPartidaController.cs
using AutoMapper;
using GerenciadorPalpites.Web.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GerenciadorPalpites.Web.Controllers
{
    [Authorize(Roles = "Gerente,Adm,Operador")]
    public class CadPartidaController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index(string ordenacao, string filtro, string termoPesquisa, string tamanhoPagina, int? page, string time, string campeonato)
        {
            #region Ordenações
            ViewBag.CurrentSort = ordenacao;
            ViewBag.DateSort = string.IsNullOrEmpty(ordenacao) ? "data desc" : "";
            ViewBag.HomeTeamSort = ordenacao == "timeCasa" ? "timeCasa desc" : "timeCasa";
            ViewBag.HomeScoreSort = ordenacao == "placarTimeCasa" ? "placarTimeCasa desc" : "placarTimeCasa";
            ViewBag.AwayTeamSort = ordenacao == "timeFora" ? "timeFora desc" : "timeFora";
            ViewBag.AwayScoreSort = ordenacao == "placarTimeFora" ? "placarTimeFora desc" : "placarTimeFora";
            ViewBag.ChampionshipSort = ordenacao == "campeonato" ? "campeonato desc" : "campeonato";
            #endregion

            var idTime = !string.IsNullOrEmpty(time) ? int.Parse(time) : -1;
            var times = TimeModel.RecuperarLista();
            times.Insert(0, new TimeModel { Id = -1, Nome = "Informe o time..." });
            ViewBag.ListaTimes = new SelectList(times, "Id", "Nome", idTime.ToString());
            ViewBag.CurrentTeam = idTime.ToString();

            var idCampeonato = !string.IsNullOrEmpty(campeonato) ? int.Parse(campeonato) : -1;
            var campeonatos = CampeonatoModel.RecuperarLista();
            campeonatos.Insert(0, new CampeonatoModel { Id = -1, Nome = "Informe o campeonato..." });
            ViewBag.ListaCampeonatos = new SelectList(campeonatos, "Id", "Nome", idCampeonato.ToString());
            ViewBag.CurrentChampionship = idCampeonato.ToString();

            #region ComboBox - Tamanho da página
            //ComboBox para definir o tamanho das páginas
            if (tamanhoPagina != null)
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, int.Parse(tamanhoPagina));
            else
            {
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
                tamanhoPagina = _quantMaxLinhasPorPagina.ToString();
            }

            ViewBag.CurrentPageSize = tamanhoPagina;
            #endregion

            if (termoPesquisa != null)
                page = 1;
            else
                termoPesquisa = filtro;

            ViewBag.CurrentFilter = termoPesquisa;

            List<PartidaViewModel> lista = Mapper.Map<List<PartidaViewModel>>(PartidaModel.RecuperarLista(filtro: termoPesquisa, ordem: ordenacao, idTime: idTime, idCampeonato: idCampeonato));

            foreach (var item in lista)
                item.DataFormatada = item.Data.ToString(new CultureInfo("pt-BR"));

            int pageNumber = (page ?? 1);
            //Retorna os registros paginados
            return View(lista.ToPagedList(pageNumber, int.Parse(tamanhoPagina)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult PartidaPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = Mapper.Map<List<PartidaViewModel>>(PartidaModel.RecuperarLista(pagina, tamPag, filtro, ordem));

            return Json(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarPartida(int id)
        {
            var vm = Mapper.Map<PartidaViewModel>(PartidaModel.RecuperarPeloId(id));

            return Json(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarQuantidadeCampeonato(int id)
        {
            var model = PartidaModel.RecuperarPeloId(id);
            if (model != null)
            {
                return Json(new { OK = true, Result = model.IdCampeonato });
            }
            else
            {
                return Json(new { OK = false });
            }
        }

        [HttpPost]
        [Authorize(Roles = "Gerente,Adm")]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirPartida(int id)
        {
            return Json(PartidaModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarPartida()
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            var model = new PartidaModel()
            {
                Id = Int32.Parse(Request.Form["Id"]),
                IdTimeCasa = Int32.Parse(Request.Form["IdTimeCasa"]),
                IdTimeFora = Int32.Parse(Request.Form["IdTimeFora"]),
                IdCampeonato = Int32.Parse(Request.Form["IdCampeonato"]),
                Data = DateTime.Parse(Request.Form["Data"]),                
                PlacarTimeCasa = Int32.Parse(Request.Form["PlacarTimeCasa"]),
                PlacarTimeFora = Int32.Parse(Request.Form["PlacarTimeFora"])
            };

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

GerenciadorPalpites.Web/Controllers/Cadastro/CadTimeController.cs
using AutoMapper;
using GerenciadorPalpites.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;

namespace GerenciadorPalpites.Web.Controllers
{
    [Authorize(Roles = "Gerente,Adm,Operador")]
    public class CadTimeController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index(string ordenacao, string filtro, string termoPesquisa, string tamanhoPagina, int? page)
        {
            ViewBag.CurrentSort = ordenacao;
            ViewBag.NameSortParam = string.IsNullOrEmpty(ordenacao) ? "nome desc" : "";
            ViewBag.CountrySortParam = ordenacao == "pais" ? "pais desc" : "pais";
            ViewBag.SportSortParam = ordenacao == "Esporte.Nome" ? "Esporte.Nome desc" : "Esporte.Nome";

            //ComboBox para definir o tamanho das páginas
            if (tamanhoPagina != null)
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, int.Parse(tamanhoPagina));
            else
            {
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
                tamanhoPagina = _quantMaxLinhasPorPagina.ToString();
            }

            ViewBag.CurrentPageSize = tamanhoPagina;

            if (termoPesquisa != null)
                page = 1;
            else
                termoPesquisa = filtro;

            ViewBag.CurrentFilter = termoPesquisa;

            //Realiza a busca completa (retorna todos os registros)
            List<TimeViewModel> lista = Mapper.Map<List<TimeViewModel>>(TimeModel.RecuperarLista(filtro: termoPesquisa, ordem: ordenacao));

            var times = TimeModel.RecuperarLista();
            times.Insert(0, new TimeModel { Id = -1, Nome = "Informe o time..." });
            ViewBag.Times = new SelectList(times, "Id", "Nome", "-1");

            int pageNumber = (page ?? 1);
            //Retorna os registros paginados
            return View(lista.ToPagedList(pageNumber, int.Parse(tamanhoPagina)));
        }
        [HttpPost]
        public JsonResult RecuperarEstatisticaTime(string idTime1, string idTime2)
        {
            var vm = Mapper.Map<EstatisticasViewModel>(EstatisticasModel.RecuperarPeloIdsTimes(int.Parse(idTime1), int.Parse(idTime2)));
            return Json(vm);
        }
    }
}

GerenciadorPalpites.Web/Controllers/Cadastro/CadUsuarioBolaoController.cs
using AutoMapper;
using GerenciadorPalpites.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace GerenciadorPalpites.Web.Controllers
{
    [Authorize(Roles = "Gerente,Adm")]
    public class CadUsuarioBolaoController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;
        private const string _senhaPadrao = "{$127;$188}";

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RecuperarUsuario(int id)
        {
            var vm = Mapper.Map<UsuarioBolaoViewModel>(UsuarioBolaoModel.RecuperarPeloId(id));

            return Json(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirUsuario(int id)
        {
            return Json(UsuarioBolaoModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SalvarUsuarioBolao(UsuarioBolaoViewModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            model.IdUsuario = UsuarioModel.RecuperarIdPeloNome(model.NomeUsuario);

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    if (BolaoModel.IsValidPassword(model.IdBolao, model.Senha))
                    {
                        var vm = Mapper.Map<UsuarioBolaoModel>(model);
                        var id = vm.Salvar();
                        if (id > 0)
                        {
                            idSalvo = id.ToString();
                        }
                        else
                        {
                            resultado = "ERRO";
                        }
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

GerenciadorPalpites.Web/Controllers/Cadastro/ClassificacaoController.cs
using AutoMapper;
using GerenciadorPalpites.Web.Models;
using PagedList;
using System.Collections.Generic;
using System.Web.Mvc;

namespace GerenciadorPalpites.Web.Controllers
{
    [Authorize(Roles = "Gerente,Adm,Operador")]
    public class ClassificacaoController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index(string ordenacao, string tamanhoPagina, int? idBolao, int? page)
        {
            ViewBag.IdBolao = idBolao ?? 0;
            ViewBag.CurrentSort = ordenacao;
            ViewBag.PosicaoSortParam = string.IsNullOrEmpty(ordenacao) ? "posicao desc" : "";
            ViewBag.TotalSortParam = ordenacao == "total" ? "total desc" : "total";
            ViewBag.VariacaoSortParam = ordenacao == "variacao" ? "variacao desc" : "variacao";
            ViewBag.NameSortParam = ordenacao == "nome" ? "nome desc" : "nome";
            ViewBag.PCSortParam = ordenacao == "placarCheio" ? "placarCheio desc" : "placarCheio";
            ViewBag.PVSortParam = ordenacao == "placarVencedor" ? "placarVencedor desc" : "placarVencedor";
            ViewBag.PPSortParam = ordenacao == "placarPerdedor" ? "placarPerdedor desc" : "placarPerdedor";
            ViewBag.AVSortParam = ordenacao == "acertouVencedor" ? "acertouVencedor desc" : "acertouVencedor";

            //ComboBox para definir o tamanho das páginas
            if (tamanhoPagina != null)
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, int.Parse(tamanhoPagina));
            else
            {
                ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
                tamanhoPagina = _quantMaxLinhasPorPagina.ToString();
            }

            ViewBag.CurrentPageSize = tamanhoPagina;

            List<ClassificacaoViewModel> lista = Mapper.Map<List<ClassificacaoViewModel>>(ClassificacaoModel.RecuperarLista(filtro: ViewBag.IdBolao, ordem: ordenacao));

            int pageNumber = (page ?? 1);
            //Retorna os registros paginados
            return View(lista.ToPagedList(pageNumber, int.Parse(tamanhoPagina)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ClassificacaoPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = Mapper.Map<List<BolaoViewModel>>(BolaoModel.RecuperarLista(User.Identity.Name, pagina, tamPag, filtro, ordem));

            return Json(lista);
        }
    }
}

GerenciadorPalpites.Web/Views/Shared/_Cadastro.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    var lista = ViewBag.Lista;
    var titulo = ViewBag.Title;

    ViewBag.Title = ViewBag.Title;
}

<link href="~/Content/bootstrap-select.css" rel="stylesheet" />
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Cadastro/BaseCadastro.css" rel="stylesheet" />

@RenderSection("Styles", true)
@RenderBody()

<div id="cadastro">
    <section id="cadastro_cabecalho">
        <h1>@ViewBag.Title</h1>
    </section>
    <section id="cadastro_conteudo">
        <div id="cabecalho_grid" class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-2">
                        <a id="btn_incluir" class="btn btn-success" role="button"><i class="glyphicon glyphicon-plus"></i> Incluir</a>
                    </div>
                    <div class="col-md-4">
                        @using (Html.BeginForm(ViewBag.ActionName as string, ViewBag.ControllerName as string, FormMethod.Get, new { @name = "FormTamPag" }))
                        {
                            @Html.DropDownList("ddl_tam_pag", (SelectList)ViewBag.ListaTamPag, new { @class = "selectpicker", @onchange = "tamanhoPaginaChanged()" })
                            @Html.Hidden("tamanhoPagina", ViewBag.CurrentPageSize as string, new { @id = "hiddenTamanhoPagina" });
                            @Html.Hidden("ordenacao", ViewBag.CurrentSort as string);
                            @Html.Hidden("filtro", ViewBag.CurrentFilter as string);
                        }
                    </div>
                    <div class="col-md-6">
                        @using (Html.BeginForm(ViewBag.ActionName as string, ViewBag.ControllerName as string, FormMethod.Get))
                        {
                            @Html.Hidden("tamanhoPagina", ViewBag.CurrentPageSize as string);
                            <div class="row">
                                <div class="col-md-8">
                                    @Html.TextBox("termoPesquisa", ViewBag.CurrentFilter as string, new { @class = "form-control", @style = "width: 250px;", placeholder = "Informe um filtro..." })
                                </div>
                                <div class="col-md-4">
                                    <button class="btn btn-info" type="submit"><i class="glyphicon glyphicon-search"></i> Pesquisar</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table id="grid_cadastro" class="table table-bordered table-striped table-hover @Html.Raw(lista == null || lista.Count == 0 ? "invisivel" : "")">
                    <thead>
                        <tr>
                            @RenderSection("TituloGrid", true)
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div id="mensagem_grid" @Html.Raw(lista != null && lista.Count > 0 ? "class=\"invisivel\"" : "")>
                    Nenhum registro em @titulo
                </div>
            </div>
        </div>
        @RenderSection("Paginacao", true)
    </section>
</div>
@Html.Hidden("id_cadastro")
<div id="modal_cadastro" class="invisivel" role="dialog">
    <div id="msg_mensagem_aviso" class="text-danger invisivel"></div>
    <fieldset>
        @Html.AntiForgeryToken()
        @RenderSection("CamposCadastro", true)
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="modal-footer">
                        <a id="btn_sair" class="btn btn-default" role="button" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i> Sair</a>
                        <a id="btn_confirmar" class="btn btn-primary" role="button"><i class="glyphicon glyphicon-ok"></i> Salvar</a>
                    </div>
                    <div id="msg_aviso" class="alert alert-warning invisivel">Falta preencher os campos acima.</div>
                    <div id="msg_erro" class="alert alert-danger invisible">Ops! Deu ruim!</div>
                </div>
            </div>
        </div>
    </fieldset>
</div>

@section Scripts{
    <script src="~/Scripts/mustache.min.js"></script>
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script src="~/Scripts/jquery.mask.min.js"></script>
    <script src="~/Scripts/Cadastro/BaseCadastro.js"></script>
    @RenderSection("Scripts", true)

    <script>
        var linhas = [];
        @{
            foreach (var item in Model)
            {
                @:linhas.push(@Html.Raw(Json.Encode(item)));
            }
        }
    </script>
}

GerenciadorPalpites.Web/Views/Shared/_CadastroSemIncluir.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    var lista = ViewBag.Lista;
    var titulo = ViewBag.Title;
}

<link href="~/Content/bootstrap-select.css" rel="stylesheet" />
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Cadastro/BaseCadastro.css" rel="stylesheet" />

@RenderSection("Styles", true)
@RenderBody()

<div id="cadastro">
    <section id="cadastro_cabecalho">
        <h1>@ViewBag.Title</h1>
    </section>
    <section id="cadastro_conteudo">
        <div id="cabecalho_grid" class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-4">
                        @RenderSection("FiltroTamanhoPagina", true)
                    </div>
                    <div class="col-md-8">
                        @using (Html.BeginForm(ViewBag.ActionName as string, ViewBag.ControllerName as string, FormMethod.Get))
                        {
                            @Html.Hidden("tamanhoPagina", ViewBag.CurrentPageSize as string);
                            <div class="row">
                                <div class="col-md-9">
                                    @Html.TextBox("termoPesquisa", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "Informe um filtro..." })
                                </div>
                                <div class="col-md-3">
                                    <button class="btn btn-info" type="submit"><i class="glyphicon glyphicon-search"></i> Pesquisar</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                @RenderSection("FiltrosAdicionais", false)
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table id="grid_cadastro" class="table table-bordered table-striped table-hover @Html.Raw(lista == null || lista.Count == 0 ? "invisivel" : "")">
                    <thead>
                        <tr>
                            @RenderSection("TituloGrid", true)
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <div id="mensagem_grid" @Html.Raw(lista != null && lista.Count > 0 ? "class=\"invisivel\"" : "")>
                    Nenhum registro em @titulo
                </div>
            </div>
        </div>
        <br />
        @RenderSection("Paginacao", true)
    </section>
</div>
@Html.Hidden("id_cadastro")

@section Scripts{
    <script src="~/Scripts/mustache.min.js"></script>
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script src="~/Scripts/jquery.mask.min.js"></script>
    <script src="~/Scripts/Cadastro/BaseCadastro.js"></script>
    @RenderSection("Scripts", true)

    <script>
        var linhas = [];
        @{
            foreach (var item in Model)
            {
                @:linhas.push(@Html.Raw(Json.Encode(item)));
            }
        }
    </script>
}

GerenciadorPalpites.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gerenciador de Palpites</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/sweetalert2.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gerenciador de Palpites", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Bolões
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Meus Bolões", "MeusBoloes", "CadBolao")</li>
                                <li>@Html.ActionLink("Bolões", "Index", "CadBolao")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Campeonatos", "Index", "CadCampeonato")</li>
                        <li>@Html.ActionLink("Partidas", "Index", "CadPartida")</li>
                        <li>@Html.ActionLink("Times", "Index", "CadTime")</li>
                    </ul>
                    using (Html.BeginForm("LogOff", "Conta", FormMethod.Post, new { id = "logoffForm" }))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Ajuda
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                                    <li>@Html.ActionLink("Regulamento", "Regulamento", "Home")</li>
                                    <li>@Html.ActionLink("Perguntas Frequentes", "PerguntasFrequentes", "Home")</li>
                                </ul>
                            </li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    @User.Identity.Name
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Alteração de senha", "AlterarSenhaUsuario", "Conta")</li>
                                </ul>
                            </li>
                            <li><a href="javascript:document.getElementById('logoffForm').submit()">Sair</a></li>
                        </ul>
                    }
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Login", "Conta")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gerenciador de Palpites</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/sweetalert2.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>